#ansible_user: admin
ansible_user: assen

microk8s_channel: 1.32/stable

SSH_AUTHORIZED_KEY: 
  - "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

VM_NAMES: 
  - mk8s-1
  - mk8s-2
  - mk8s-3
VM_CPUS: 8
VM_MEMORY_MB: 8192
VM_DISK_GB: 100
VM_MEMORY: 8G
VM_DISK: 100G
VM_OSD_DISK: 60G

FIRST_NODE_LIST: "{{[ VM_NAMES[0] ]}}"
JOIN_NODE_LIST: "{{ VM_NAMES | difference(FIRST_NODE_LIST) }}"

DOMAIN: local

SERVICE_DOMAINS: 
  - dashboard.{{DOMAIN}}
  - grafana.{{DOMAIN}}
  - prometheus.{{DOMAIN}}
  - portainer.{{DOMAIN}}
  - graylog.{{DOMAIN}}
  - alertmanager.{{DOMAIN}}
  - rabbitmq.{{DOMAIN}}
  - tbmq.{{DOMAIN}}
  - zipkin.{{DOMAIN}}
  - coherence.{{DOMAIN}}
  - spring-boot-admin.{{DOMAIN}}
  - spring-cloud-config.{{DOMAIN}}
  - spring-cloud-gateway.{{DOMAIN}}

#192.168.91.157 dashboard.local grafana.local prometheus.local portainer.local graylog.local alertmanager.local rabbitmq.local tbmq.local zipkin.local coherence.local spring-boot-admin.local spring-cloud-config.local spring-cloud-gateway
  