- name: Get microk8s cluster members
  theko2fi.multipass.multipass_vm_exec:
    name: "{{VM_NAMES[0]}}"
    command: "microk8s kubectl get node -o 'jsonpath={.items[*].metadata.name}'"
  register: cluster_node_names

- name: Check if {{join_node}} is already microk8s cluster member
  set_fact:
    not_member: "{{ cluster_node_names.stdout_lines[0].find(join_node) == -1 }}"

- name: Get microk8s cluster add-node command for {{join_node}}
  theko2fi.multipass.multipass_vm_exec:
    name: "{{VM_NAMES[0]}}"
    command: "microk8s add-node --format short"
  register: add_node_command
  when: not_member

- name: Join {{join_node}} to microk8s cluster
  theko2fi.multipass.multipass_vm_exec:
    name: "{{join_node}}"
    command: "{{add_node_command.stdout_lines[0]}}"
  when: not_member