apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-web
  namespace: rabbitmq
spec:
  rules:
  - host: rabbitmq.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rabbitmq
            port:
              number: 15672
  #tls:
  #  - hosts: 
  #    - kubernetes-dashboard.localtest.me
  #    secretName: kubernetes-dashboard.localtest.me