

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-service-monitor
  namespace: observability
  labels:
    team: observability
    release: kube-prom-stack
spec:
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 10s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - rabbitmq
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/component: rabbitmq
      