apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage
  namespace: coherence
spec:
  #cluster: storage-cluster
  coherence:
    #cacheConfig: storage-cache-config.xml
    #overrideConfig: tangosol-coherence-override.xml
    storageEnabled: true
    logLevel: 3
    persistence:
      mode: active
      persistentVolumeClaim:     
        storageClassName: ceph-rbd
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    jvm:
      #args:
      #  - "-XX:+UseZGC"
      #  - "-XX:+ZGenerational"
      #  - "-XX:ZUncommitDelay=30"
      memory:
        percentage: 80
        #initialRAMPercentage: 10
        #minRAMPercentage: 5.75
        #maxRAMPercentage: 75
      gc:
        collector: "G1"
        logging: true
      debug:
        enabled: true
        port: 5005      
        suspend: false
    metrics:
      enabled: true 
  env:
    - name: "COHERENCE_METRICS_LEGACY_NAMES"
      value: "false"
  ports:
    - name: extend
      port: 20000
    - name: metrics
      serviceMonitor:
        enabled: true
        #additionalLabels: 
        #    team: observability
        #    release: kube-prom-stack
  initResources:           
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  resources:
      requests:
        memory: "1907Mi"
        cpu: "250m"
      limits:
        memory: "3814Mi"
        cpu: "500m"
---

apiVersion: v1
kind: Service
metadata:
  name: storage-rest
  namespace: coherence
  labels:
      coherenceCluster: storage
      coherenceComponent: coherence-rest
      coherenceDeployment: storage
      coherencePort: rest
      coherenceRole: storage
spec:
  ports:
    - name: rest
      protocol: TCP
      appProtocol: http
      port: 30000
      targetPort: 30000
  type: NodePort    
  selector:
    coherenceCluster: storage
    coherenceComponent: coherencePod
    coherenceDeployment: storage
    coherenceRole: storage
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: coherence
  namespace: coherence
  labels:
    team: observability
    release: kube-prom-stack
spec:
  endpoints:
    - port: metrics
      scrapeTimeout: 10s
      relabelings:
        - action: labeldrop
          regex: (endpoint|instance|job|service)
  namespaceSelector:
    matchNames:
      - coherence
  selector:
    matchLabels:
      coherenceCluster: storage
      coherenceComponent: coherence-service
      coherenceDeployment: storage
      coherencePort: metrics
      coherenceRole: storage

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: storage-rest
  namespace: coherence
spec:
  rules:
  - host: coherence.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: storage-rest
            port:
              number: 30000
