- name: Remove HA mikrok8s cluster
  hosts: localhost
  connection: local
  gather_facts: true
  become: false
  tasks:
    - name: Create miltipass VMs
      theko2fi.multipass.multipass_vm:
        name: "{{item}}"
        state: absent
        purge: true
      with_items: "{{ VM_NAMES }}"

- name: Remove service domains from hosts file
  become: true
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    state: absent
  with_items: "{{ SERVICE_DOMAINS }}"