- name: Install Coherence
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Create Coherence namespace
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Namespace
          apiVersion: v1
          metadata:
            name: coherence
            labels:
              metrics: enabled
    
    - name: Install Coherence Operator
      kubernetes.core.k8s:
        src: https://github.com/oracle/coherence-operator/releases/download/v3.4.0/coherence-operator.yaml
        state: present

    - name: Wait for operator deployment avaiablity
      kubernetes.core.k8s:
        namespace: coherence
        name: coherence-operator-controller-manager
        kind: Deployment
        wait: yes
        wait_sleep: 2
        wait_timeout: 100
        wait_condition:
          type: Available
          status: true

    - name: Deploy coherence cluster
      kubernetes.core.k8s:
          src: tasks/coherence/deployment.yml
          state: present

    - name: Find all Coherence dashboards
      ansible.builtin.find:
        paths: tasks/coherence/grafana
      register: files

    - name: Create Coherence Grafana folder
      community.grafana.grafana_folder:
        url: http://grafana.local
        grafana_user: "admin"
        grafana_password: "prom-operator"
        title: "Coherence"
        state: present    

    - name: Import Coherence Grafana dashboards
      community.grafana.grafana_dashboard:
        grafana_url: http://grafana.local
        grafana_user: "admin"
        grafana_password: "prom-operator"
        folder: "Coherence"
        state: present
        overwrite: false
        path: "{{item}}"
      with_items: "{{ files.files |  map(attribute='path') }}"
      ignore_errors: true