- name: Provision VMWare Fusion VMs
  hosts: localhost
  connection: local
  gather_facts: true
  become: false
  
  vars:
    username: "admin"
    password: "Fus10n_Admin"
    api_url: "http://127.0.0.1"
    api_port: "8697"
    validate_certs: no

  tasks:
    - name: List VMWare Fustion VMs
      qsypoq.vmware_desktop.unix_vmware_desktop_vminfos:
        username: "{{username}}"
        password: "{{password}}"
      register: vminfos
    
    - name: Set VMs VMX path fact
      set_fact:
        vmx_paths: "{{vminfos.msg | map(attribute='path')}}"

  
    - name: Stop VMs headeless
      command: "vmrun -T fusion stop '{{item}}' nogui"
      with_items: "{{vmx_paths}}"
