- name: Provision VMWare Fusion VMs
  hosts: localhost
  connection: local
  gather_facts: true
  become: false
  
  vars:
    username: "admin"
    password: "Fus10n_Admin"
    api_url: "http://127.0.0.1"
    api_port: "8697"
    validate_certs: no
  
  collections:
    - qsypoq.vmware_desktop

  roles:
    - fusion  
  # tasks:
  #   - name: "List VMWare Fustion VMs"
  #     unix_vmware_desktop_vminfos:
  #       username: "{{username}}"
  #       password: "{{password}}"
  #     register: vminfos
  #   - name: Print VMWare Fustion VM Info
  #     ansible.builtin.debug:
  #       msg: "{{vminfos}}"
        
  #   - name: "Register VM with name ansible_test2"
  #     unix_vmware_desktop_vmmgmt:
  #       name: "mk8s-1"
  #       action: register
  #       vmx_path: 'C:\Users\Qsypoq\Documents\Virtual Machines\ansible_test2\svc_pfSense.vmx'
  #       username: "{{username}}"
  #       password: "{{password}}"