- name: Install Graylog
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Add Graylog helm repository
      kubernetes.core.helm_repository:
        name: kongz
        repo_url: "https://charts.kong-z.com"
    
    - name: Add MongoDB helm repository
      kubernetes.core.helm_repository:
        name: mongodb
        repo_url: https://mongodb.github.io/helm-charts

    - name: Create Graylog namespace
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Namespace
          apiVersion: v1
          metadata:
            name: graylog
            labels:
              metrics: enabled

    - name: Install MongoDB community operator
      kubernetes.core.helm:
        name: community-operator
        chart_ref: mongodb/community-operator
        release_namespace: graylog

    - name: Install MongoDB 
      kubernetes.core.k8s:
        namespace: graylog
        src: tasks/graylog/mongodb.yml
        state: present 

    - name: Install Graylog
      kubernetes.core.helm:
        name: graylog
        chart_ref: kongz/graylog
        release_namespace: graylog
        values_files:
          - tasks/graylog/values.yml
      register: result

    - name: Install Graylog Service Monitor 
      kubernetes.core.k8s:
        namespace: graylog
        src: tasks/graylog/servicemonitor.yml
        state: present 

    - debug:
        msg: "{{ result.stdout }}"


