- name: Install Graylog
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Add Graylog heml repository
      kubernetes.core.helm_repository:
        name: kongz
        repo_url: "https://charts.kong-z.com"
  
    - name: Create Graylog namespace
      kubernetes.core.k8s:
        name: graylog
        api_version: v1
        kind: Namespace
        state: present

    - name: Install mongodb
      import_tasks: tasks/graylog/mongodb.yml

    - name: Install Graylog    
      kubernetes.core.helm:
        name: graylog
        chart_ref: kongz/graylog
        release_namespace: graylog
        values_files:
          - tasks/graylog/resources/values.yml
      register: result

    - debug:
        msg: "{{ result.stdout }}"


