- name: Install Graylog
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Add Graylog helm repository
      kubernetes.core.helm_repository:
        name: kongz
        repo_url: "https://charts.kong-z.com"
    
    - name: Add MongoDB helm repository
      kubernetes.core.helm_repository:
        name: mongodb
        repo_url: https://mongodb.github.io/helm-charts

    - name: Create Graylog namespace
      kubernetes.core.k8s:
        name: graylog
        api_version: v1
        kind: Namespace
        state: present

    - name: Install MongoDB community operator    
      kubernetes.core.helm:
        name: community-operator
        chart_ref: mongodb/community-operator
        release_namespace: graylog

    - name: Install MongoDB 
      kubernetes.core.k8s:
        namespace: graylog
        src: tasks/graylog/resources/mongodb.yml
        state: present 

    - name: Install Graylog    
      kubernetes.core.helm:
        name: graylog
        chart_ref: kongz/graylog
        release_namespace: graylog
        values_files:
          - tasks/graylog/resources/values.yml
      register: result

    - debug:
        msg: "{{ result.stdout }}"


