- name: Install microceph
  hosts: ceph
  gather_facts: false
  become: true
  tasks:
    - name: Install microceph
      community.general.snap:
        name: microceph
        channel: latest/edge

- name: Bootstrap microceph cluster
  hosts: ceph-bootstrap
  gather_facts: false
  become: true
  tasks:
    - name: Get microceph status
      command: microceph status
      register: status
      ignore_errors: true
    - debug:
        var: status.stdout_lines
    - name: Bootstrap microceph
      command: "microceph cluster bootstrap"
      when: status.stderr 
      #is search("Error:"Database is not yet initialized")
    - name: Get microceph cluster status
      shell: microceph status
      register: status
      retries: 5
      delay: 2
      until: status.stdout is search("MicroCeph deployment summary") 
    - debug:
        var: status.stdout_lines
      when: status.stdout is not search("MicroCeph deployment summary") 

- name: Join microceph cluster
  hosts: ceph-nodes
  gather_facts: false
  become: true
  tasks:
    - include_tasks: tasks/microceph/join.yml

- name: Provision microceph OSD storage
  hosts: ceph
  gather_facts: false
  become: true
  tasks:
    - include_tasks: tasks/microceph/osd.yml

- name: Configure microceph cluster
  hosts: ceph-bootstrap
  gather_facts: false
  become: true
  tasks:
    - command: microceph.ceph config set global osd_pool_default_size 2                               
    - command: microceph.ceph config set mgr mgr_standby_modules false                                                                                                                                                      
    - command: microceph.ceph config set osd osd_crush_chooseleaf_type 0