- name: Install microk8s cluster and dashboard
  hosts: microk8s
  gather_facts: false
  become: true
  tasks: 
    - include_tasks: tasks/microk8s/install.yml

- name: Join microk8s cluster
  hosts: microk8s-nodes
  gather_facts: false
  become: true
  tasks:
    - include_tasks: tasks/microk8s/join.yml

- name: Get microk8s kubectl configuration
  gather_facts: false
  hosts: microk8s-bootstrap
  become: false
  tasks:
    - include_tasks: tasks/microk8s/kubectl.yml

- name: Install microk8s dashboard
  gather_facts: false
  hosts: microk8s-bootstrap
  become: true
  tasks:
    - include_tasks: tasks/microk8s/dashboard.yml

- name: Add dasestherhboard admin user 
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - include_tasks: tasks/microk8s/dashboard-admin-user.yml

- name: Add token to kubectl config
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - include_tasks: tasks/microk8s/kubectl-token.yml

- name: "Add --enable-ssl-passthrough to nginx-ingress-microk8s-controller"
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - include_tasks: tasks/microk8s/ingress-ssl-passthrough.yml