- name: Install HA mikrok8s cluster
  hosts: localhost
  connection: local
  gather_facts: true
  become: false
  roles:
    # - homebrew
    # - cert
    - multipass
    - microceph
    # - microk8s
    # - microk8s-dashboard
    # - microk8s-portainer
    # - microk8s-observability
    # - microk8s-whereabouts
    # - microk8s-macvlan
    # - ubuntu
