- name: Generate microk8s SSL certificates
  hosts: localhost
  connection: local
  gather_facts: true
  become: false
  tasks:
    - include_tasks: tasks/cert/generate.yml

- name: Install microk8s
  hosts: microk8s
  gather_facts: false
  become: true
  tasks: 
    - include_tasks: tasks/microk8s/install.yml

- name: Join microk8s cluster
  hosts: microk8s-nodes
  gather_facts: false
  become: true
  tasks:
    - include_tasks: tasks/microk8s/join.yml

- name: Get microk8s kubectl configuration
  gather_facts: false
  hosts: microk8s-bootstrap
  become: false
  tasks:
    - include_tasks: tasks/microk8s/kubectl.yml

- name: Configure microk8s cluster
  gather_facts: false
  hosts: microk8s-bootstrap
  become: true
  tasks:
    - include_tasks: tasks/microk8s/plugins.yml

# TODO: move to a task
- name: Add dashboard admin user 
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  roles:
    - microk8s-dashboard   

- name: Connect microk8s to external ceph
  gather_facts: false
  hosts: microk8s-bootstrap
  become: true
  tasks:
    - include_tasks: tasks/microk8s/ceph.yml

- name: Configure microceph as default storage class in microk8s
  hosts: localhost
  connection: local
  gather_facts: true
  become: false
  tasks:
    - include_tasks: tasks/microk8s/ceph-sc.yml

- name: Install microk8s portainer plugin
  gather_facts: false
  hosts: microk8s-bootstrap
  become: true
  tasks:
    - name: Install microk8s portainer plugin
      command: "/snap/bin/microk8s.enable portainer --storage-class=ceph-rbd"

- name: Install portainer agents and ingress
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  roles:  
    - microk8s-portainer


# # - name: Install microk8s observability services
# #   hosts: microk8s-bootstrap
# #   gather_facts: false
# #   become: true
# #   roles:
# #     - microk8s-observability

# # - name: Install microk8s multus plugin
# #   gather_facts: false
# #   hosts: microk8s-bootstrap
# #   become: true
# #   tasks:
# #     - name: Install microk8s portainer plugin
# #       command: "/snap/bin/microk8s.enable multus"

# # - name: Install microk8s macvlan and whereabouts
# #   hosts: localhost
# #   connection: local
# #   gather_facts: false
# #   become: false
# #   roles:
# #     - microk8s-macvlan
# #     - microk8s-whereabouts
# #     - ubuntu
