- name: Provision microk8s VMs
  hosts: localhost
  connection: local
  gather_facts: true
  become: false
  tasks:
    - name: Install multipass
      community.general.homebrew:
        name: multipass
        state: present
    - name: Install kubectl
      community.general.homebrew:
        name: kubectl
        state: present
    - name: Install helm
      community.general.homebrew:
        name: helm
        state: present

  roles:
    - multipass
