- name: Stop HA mikrok8s cluster VMs
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Stop multipass VMs
      theko2fi.multipass.multipass_vm:
        name: "{{item}}"
        state: stopped
      with_items: "{{ VM_NAMES }}"
      ignore_errors: true
    