---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multicast
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "multicast",
    "type": "bridge",
    "bridge": "br100",
    "isDefaultGateway": false,
    "forceAddress": false,
    "ipMasq": false,
    "hairpinMode": false,
    "ipam": {
      "type": "host-local",
      "subnet": "192.168.224.0/24",
      "rangeStart": "192.168.224.2",
      "rangeEnd": "192.168.224.250",
      "routes": [
        { "dst": "0.0.0.0/0" }
      ],
      "gateway": "192.168.224.1"
    }
  }'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
  #namespace: default
  labels:
    app: netshoot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netshoot
  strategy: {}
  template:
    metadata:
      labels:
        app: netshoot
      annotations:
        k8s.v1.cni.cncf.io/networks: multicast
        # '[
        #     { 
        #       "name" : "multicast",
        #       "interface": "eth1"
        #     }
        # ]'
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        command: ["/bin/sleep", "3650d"]
        resources: 
