- name: Install RabbitMQ Cluster
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Create RabbitMQ namespace
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Namespace
          apiVersion: v1
          metadata:
            name: rabbitmq
            labels:
              metrics: enabled

    - name: Add RabbitMQ helm repository
      kubernetes.core.helm_repository:
        repo_url: https://charts.bitnami.com/bitnami
        name: bitnami

    - name: Install RabbitMQ Cluster operator
      kubernetes.core.helm:
        name: rabbitmq-system
        chart_ref: bitnami/rabbitmq-cluster-operator
        release_namespace: rabbitmq-system
        create_namespace: true

    - name: Install RabbitMQ cluster
      kubernetes.core.k8s:
        src: tasks/rabbitmq/rabbitmq.yml
        state: present

    # - name: Import RabbitMQ Grafana dashboards
    #   shell: "./grafana-import.sh -u admin -w prom-operator -d tasks/rabbitmq/grafana -t grafana.local"
