---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: home-network
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "home-network",
    "type": "bridge",
    "bridge": "br100",
    "isDefaultGateway": false,
    "forceAddress": false,
    "ipMasq": false,
    "hairpinMode": false,
    "ipam": {
      "type": "host-local",
      "subnet": "192.168.1.0/24",
      "rangeStart": "192.168.1.201",
      "rangeEnd": "192.168.1.250",
      "routes": [
        { "dst": "0.0.0.0/0" }
      ],
      "gateway": "192.168.1.1"
    }
  }'
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: multus
  name: test-1
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {
         "name" : "home-network",
         "interface": "eth1",
         "ips": ["192.168.1.205"]
      }
    ]'
spec:
  containers:
    - name: netshot
      image: nicolaka/netshoot
      command: ["/bin/sleep", "3650d"]
  restartPolicy: Always
---

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: multus
  name: test-2
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {
         "name" : "home-network",
         "interface": "eth1",
         "ips": ["192.168.1.206"]
      }
    ]'
spec:
  containers:
    - name: netshot
      image: nicolaka/netshoot
      command: ["/bin/sleep", "3650d"]
  restartPolicy: Always