- name: Install Zipkin
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Create Zipkin namespace
      kubernetes.core.k8s:
        name: zipkin
        api_version: v1
        kind: Namespace
        state: present

    - name: Add Zipkin helm repository
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: "https://charts.bitnami.com/bitnami"
    
    - name: Install Zipkin
      kubernetes.core.helm:
        name: zipkin
        chart_ref: oci://registry-1.docker.io/bitnamicharts/zipkin
        release_namespace: zipkin
        values_files:
          - tasks/zipkin/values.yml
      register: result

    - debug:
        msg: "{{ result.stdout }}"


