apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster-metrics
  namespace: kafka
  labels:
    kafkaCluster: kafka-cluster
spec:
  ports:
    - name: metrics
      protocol: TCP
      appProtocol: http
      port: 9404
      targetPort: 9404
  selector:
    app.kubernetes.io/name: kafka-exporter
    app.kubernetes.io/instance: kafka-cluster
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka
  namespace: kafka
  labels:
    team: observability
    release: kube-prom-stack
spec:
  endpoints:
    - port: metrics
      scrapeTimeout: 10s
      relabelings:
        - action: labeldrop
          regex: (endpoint|instance|job|service)
  namespaceSelector:
    matchNames:
      - kafka
  selector:
    matchLabels:
      kafkaCluster: kafka-cluster
