apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-user
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: test
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
        host: "*"
      - resource:
          type: topic
          name: kafka
          patternType: prefix
        operations:
          - Create
          - Describe
          - Write
        host: "*"
      - resource:
          type: topic
          name: imdg
          patternType: prefix
        operations:
          - Create
          - Describe
          - Write
        host: "*"