apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
  namespace: default
  labels:
    app: netshoot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netshoot
  strategy: {}
  template:
    metadata:
      labels:
        app: netshoot
      annotations:
        k8s.v1.cni.cncf.io/networks: whereabouts-conf
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        command: ["/bin/sleep", "3650d"]
        resources: {}
