- name: Install microk8s 
  command: "snap install microk8s --classic"

- name: Create microk8s group
  ansible.builtin.group:
    name: microk8s
    state: present

- name:  Append ansible_user user to the microk8s group
  ansible.builtin.user:
    name: "{{ansible_user}}"
    groups: microk8s
    append: true 
