- name: Install microk8s 
  command: "sudo snap install microk8s --classic"

- name: Append ununtu user to the microk8s group
  ansible.builtin.user:
    name: ubuntu
    groups: microk8s
    append: true 
