

- name: Copy observability helm chart values 
  copy:
    src: "{{playbook_dir}}/roles/microk8s-observability/resources/values.yml"
    dest: "/home/{{ansible_user}}/values.yml"

- name: Install microk8s observability plugin
  shell: "/snap/bin/microk8s.enable observability --kube-prometheus-stack-values=/home/{{ansible_user}}/values.yml"
  retries: 10
  delay: 2
  register: result
  until: result.stdout

- debug:
    msg: "{{ result.stdout_lines }}"
