- name: Install microceph
  theko2fi.multipass.multipass_vm_exec:
    name: "{{item}}"
    command: "sudo snap install microceph --channel=latest/edge"
  with_items: "{{ VM_NAMES }}"

- name: Get microceph cluster status
  theko2fi.multipass.multipass_vm_exec:
    name: "{{VM_NAMES[0]}}"
    command: "sudo microceph status"
  register: status
  ignore_errors: true
  ignore_unreachable: true

- name: Display ceph cluster status
  ansible.builtin.debug:
    var: status

- name: Bootstrap microceph
  theko2fi.multipass.multipass_vm_exec:
    name: "{{VM_NAMES[0]}}"
    command: "sudo microceph cluster bootstrap"
  when: status.stdout is undefined or status.stdout is not search(VM_NAMES[0])

- name: Join nodes to microceph cluster
  ansible.builtin.include_role:
    name: microceph-member
  loop: "{{ JOIN_NODE_LIST }}"
  loop_control:
    loop_var: join_node