- name: Install multipass
  community.general.homebrew:
    name: multipass
    state: present

- name: Install openssl
  community.general.homebrew:
    name: openssl
    state: present

- name: Install kubectl
  community.general.homebrew:
    name: kubectl
    state: present

- name: Install helm
  community.general.homebrew:
    name: helm
    state: present