- name: Get tart VMs facts
  hosts: localhost
  connection: local
  gather_facts: true
  become: false
  tasks:  
    - name: List tart VMs
      command: "tart list --format json"
      register: vm_list

    - name: Set running tart VM names fact
      set_fact:
        vms: "{{vm_list.stdout | from_json | selectattr('Source', '==', 'local') | selectattr('State', '==', 'stopped') }}"

    - name: Start tart VMs
      include_tasks: ../tasks/tart/start.yml
      loop: "{{ vms }}"



