- name: Configure hostname 
  ansible.builtin.hostname:
    name: "{{inventory_hostname_short}}"

- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - system

- name: Upgrade system
  apt:
    upgrade: full

- name: Install packages
  apt: "name={{item}}"
  with_items:
    - libnss-mdns 
    - avahi-utils
    - ntp
    - dnsutils 
    - iperf 
    - net-tools 
    #- iproute2
    #- iputils-ping 

- name: Configure mDNS
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^MulticastDNS='  
    line: MulticastDNS=yes

- name: Set authorized key
  ansible.posix.authorized_key:
    user: "{{ansible_user}}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Set sysctl properties
  sysctl:
    name: "{{item.name}}"
    value: "{{item.value}}"
    state: present
  with_items:
    - { name: "net.ipv4.conf.all.rp_filter", value: "1" }

- name: iptables -P FORWARD ACCEPT
  command: iptables -P FORWARD ACCEPT

- name: Save microk8s kubectl config
  ansible.builtin.file:
    path: /etc/rc.local
    mode: '0755'
    state: touch

- name: Save microk8s kubectl config
  copy:
    dest: /etc/rc.local
    content: |
      #!/bin/sh
      iptables -P FORWARD ACCEPT


