- name: Configure hostname 
  ansible.builtin.hostname:
    name: "{{inventory_hostname_short}}"

- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - system

- name: Upgrade system
  apt:
    upgrade: full

- name: Install libnss-mdns
  apt: name=libnss-mdns
  with_items:
    - libnss-mdns 
    - avahi-utils
    - ntp
    - iputils-ping 
    - dnsutils 
    - iperf 
    - net-tools 
    - iproute2

- name: Configure mDNS
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^MulticastDNS='  
    line: MulticastDNS=yes

- name: Set authorized key
  ansible.posix.authorized_key:
    user: "{{ansible_user}}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"