- name: Configure hostname 
  ansible.builtin.hostname:
    name: "{{inventory_hostname}}"

- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - system

- name: Upgrade system
  apt:
    upgrade: full

- name: Install libnss-mdns
  apt: name=libnss-mdns

- name: Install avahi-utils
  apt: name=avahi-utils

- name: Install ntp
  apt: name=ntp


- name: Configure mDNS
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^MulticastDNS='  
    line: MulticastDNS=yes

- name: Set authorized key
  ansible.posix.authorized_key:
    user: "{{ansible_user}}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"