- name: Configure microk8s addons git
  command: "sudo git config --global --add safe.directory /snap/microk8s/current/addons/community/.git"

- name: Add rook-release heml repo
  command: "sudo microk8s helm repo add rook-release https://charts.rook.io/release"

- name: Update microk8s helm repo
  command: "sudo microk8s helm repo update"

- name: Install microk8s hostpath-storage plugin
  shell: "sudo /snap/bin/microk8s.enable hostpath-storage"
  retries: 10
  delay: 2
  register: result

- name: Install microk8s rook-ceph plugin
  shell: "sudo /snap/bin/microk8s.enable rook-ceph"
  retries: 10
  delay: 2
  register: result

- debug: 
    msg: "{{ result.stdout_lines }}"
      
- name: Check is already connected to cluster
  shell: "sudo microk8s kubectl --namespace rook-ceph-external get cephcluster"
  retries: 30
  delay: 2
  register: cephcluster

- name: Connect external ceph
  command: "sudo microk8s connect-external-ceph"  
  register: result2
  when: cephcluster.stdout is not search("Cluster connected successfully")

- debug: 
    msg: "{{ result2.stdout_lines }}"
  when: cephcluster.stdout is not search("Cluster connected successfully")  

- name: Wait for cluster connection
  shell: sudo microk8s kubectl --namespace rook-ceph-external get cephcluster
  register: result3
  retries: 100
  delay: 2
  until: result3.stdout is search("Cluster connected successfully")
  when: cephcluster.stdout is not search("Cluster connected successfully")