- name: Configure microk8s addons git
  command: "git config --global --add safe.directory /snap/microk8s/current/addons/community/.git"

- name: Enable micropeh rook-ceph plugin
  command: "microk8s.enable rook-ceph"  

- name: Add rook-release heml repo
  command: "microk8s helm repo add rook-release https://charts.rook.io/release"

- name: Update microk8s helm repo
  command: "microk8s helm repo update"

- name: Connect external ceph
  command: "microk8s connect-external-ceph"  