- name: Install microk8s 
  community.general.snap:
    name: microk8s
    classic: true

- name: Create microk8s group
  ansible.builtin.group:
    name: microk8s
    state: present

- name: Add ansible user to mikcrok8s group
  ansible.builtin.user:
    name: "{{ansible_user}}"
    groups: microk8s
    append: yes

# - name: Install microk8s plugins
#   include_tasks: tasks/microk8s/plugins.yml
