- name: Install microk8s plugins
  command: "/snap/bin/microk8s.enable {{ item }}"
  with_items:
    - ingress
    - rbac
    - dashboard
    - community
    - multus
    #- hostpath-storage
    #- portainer
    