- name: Install microk8s plugins
  command: "/snap/bin/microk8s.enable {{ item }}"
  with_items:
    - community
    - dashboard --hostname=dashboard.local
    - hostpath-storage
    - rook-ceph
    - rbac
    
   

    