- name: List VMWare Fustion VMs
  qsypoq.vmware_desktop.unix_vmware_desktop_vminfos:
    username: "{{username}}"
    password: "{{password}}"
  register: vminfos

- name: Print VMWare Fustion VM Info
  ansible.builtin.debug:
    msg: "{{vminfos}}"

- name: Get infos of all the configured vmnets
  qsypoq.vmware_desktop.unix_vmware_desktop_netmgmt:
    username: "{{username}}"
    password: "{{password}}"
    action: infos
  register: netmgmt

- name: Get VM Nets
  set_fact:
    vmnets_json: "{{ netmgmt | to_json | from_json }}"

- name: Get NAT VM Net name
  set_fact:
    vmnets: "{{ vmnets_json.msg.vmnets | community.general.json_query('[?type==`nat`].name') }}"

- name: Print VMWare Fustion VM Nets
  ansible.builtin.debug:
    var: vmnets
#   msg: "{{vmnets | community.general.json_query('[?type==`nat`].name') }}"

# - name: Print VMWare Fustion VM Nets
#   ansible.builtin.debug:
#     var: vmnets_json[1]
    #community.general.json_query(query) }}


    # - name: "Register VM with name ansible_test2"
    #   unix_vmware_desktop_vmmgmt:
    #     name: "mk8s-1"
    #     action: register
    #     vmx_path: 'C:\Users\Qsypoq\Documents\Virtual Machines\ansible_test2\svc_pfSense.vmx'
    #     username: "{{username}}"
    #     password: "{{password}}"