- name: Enable micropeh rook-ceph plugin
  command: "microk8s.enable rook-ceph"  

- name: Add rook-release heml repo
  command: "microk8s helm repo add rook-release https://charts.rook.io/release"

- name: Update microk8s helm repo
  command: "microk8s helm repo update"

- name: Connect external ceph
  command: "microk8s connect-external-ceph"  

# - name: Change  microk8s-hostpath StorageClass not to be deault
#   kubernetes.core.k8s:
#     api_version: storage.k8s.io/v1
#     kind: StorageClass
#     name: microk8s-hostpath
#     state: patched
#     definition:
#       metadata:
#         annotations:
#           "storageclass.kubernetes.io/is-default-class" : "false"

# - name: Change the default StorageClass to ceph-rbd
#   kubernetes.core.k8s:
#     api_version: storage.k8s.io/v1
#     kind: StorageClass
#     name: ceph-rbd
#     namespace: rook-ceph-external
#     state: patched
#     definition:
#       metadata:
#         annotations:
#           "storageclass.kubernetes.io/is-default-class" : "true"
    

#kubectl patch storageclass ceph-rbd -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
