- name: Change  microk8s-hostpath StorageClass not to be deault
  kubernetes.core.k8s:
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: microk8s-hostpath
    state: patched
    definition:
      metadata:
        annotations:
          "storageclass.kubernetes.io/is-default-class" : "false"

- name: Change the default StorageClass to ceph-rbd
  kubernetes.core.k8s:
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: ceph-rbd
    namespace: rook-ceph-external
    state: patched
    definition:
      metadata:
        annotations:
          "storageclass.kubernetes.io/is-default-class" : "true"

#kubectl patch storageclass ceph-rbd -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
