- name: Create clould-init
  template:
    src: "{{playbook_dir}}/roles/multipass/resources/node-template.yml"
    dest: "{{playbook_dir}}/roles/multipass/resources/node.yml"

- name: Create multipass VMs
  theko2fi.multipass.multipass_vm:
    name: "{{item}}"
    cpus: "{{VM_CPUS}}"
    memory: "{{VM_MEMORY}}"
    disk: "{{VM_DISK}}"
    cloud_init: "{{playbook_dir}}/roles/multipass/resources/node.yml"
    state: present
    purge: true
  with_items: "{{ VM_NAMES }}"

- name: Add the VM to the inventory
  ansible.builtin.add_host:
    name: "{{item}}"
    groups: multipass
    ansible_host: "{{item}}"
    ansible_connection: theko2fi.multipass.multipass
  with_items: "{{ VM_NAMES }}"


- name: Display inventory
  ansible.builtin.debug:
    var: groups['multipass']

- name: Remove service domains from hosts file
  become: true
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    state: absent
  with_items: "{{ SERVICE_DOMAINS }}"

- name: Add VM IP to /etc/hosts
  ansible.builtin.include_role:
    name: roles/multipass-hosts
  loop: "{{ VM_NAMES }}"
  loop_control:
    loop_var: node