- name: Install microk8s plugins
  theko2fi.multipass.multipass_vm_exec:
    name: "{{ VM_NAMES[0] }}"
    command: "/snap/bin/microk8s.enable portainer --storage-class ceph-rbd"
  

- name: Create Portainer ingress
  kubernetes.core.k8s:
    state: present
    src: ./resources/ingress.yml

- name: Create Portainer agent
  kubernetes.core.k8s:
    state: present
    src: https://downloads.portainer.io/ce2-21/portainer-agent-k8s-nodeport.yaml