- name: Get microk8s kubectl config
  command: "microk8s config view"
  register: result

- name: Create .kube directory 
  file: 
    path: "~/.kube"
    state: directory

- name: Save microk8s kubectl config
  ansible.builtin.copy:
    content: "{{result.stdout}}"
    dest: ~/.kube/config
  