- name: Add MongoDB heml repository
  kubernetes.core.helm_repository:
    name: mongodb
    repo_url: "https://mongodb.github.io/helm-charts"

- name: Install MongoDB community operator    
  kubernetes.core.helm:
    name: community-operator
    chart_ref: mongodb/community-operator
    release_namespace: graylog

- name: Install MongoDB 
  kubernetes.core.k8s:
    namespace: graylog
    src: tasks/graylog/resources/mongodb.yml
    state: present

